<?php

return [
    'default' => env('DB_CONNECTION', 'mysql'),

    'connections' => [
        'sip' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST_SIP'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE_SIP'),
            'username'  => env('DB_USERNAME_SIP'),
            'password'  => env('DB_PASSWORD_SIP'),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
            'strict'    => true,
            'engine'    => null,
        ],
        'ips' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST_IPS'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE_IPS'),
            'username'  => env('DB_USERNAME_IPS'),
            'password'  => env('DB_PASSWORD_IPS'),
            // 'charset'   => 'utf8mb3',
            // 'collation' => 'utf8mb3_general_ci',
            'prefix'    => '',
            'strict'    => true,
            'engine'    => null,
        ],
        'spm' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST_SPM'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE_SPM'),
            'username'  => env('DB_USERNAME_SPM'),
            'password'  => env('DB_PASSWORD_SPM'),
            'charset'   => 'latin1',
            'collation' => 'latin1_swedish_ci',
            'prefix'    => '',
            'strict'    => true,
            'engine'    => null,
        ],
        'sma' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST_SMA'),
            'port'      => env('DB_PORT', '3306'),
            'database'  => env('DB_DATABASE_SMA'),
            'username'  => env('DB_USERNAME_SMA'),
            'password'  => env('DB_PASSWORD_SMA'),
            'charset'   => 'latin1',
            'collation' => 'latin1_swedish_ci',
            'prefix'    => '',
            'strict'    => true,
            'engine'    => null,
        ],
    ],
];
